SELECT MATERIAL_COD,MATERIAL_DESCRIPCION,MATERIAL_PRECIO from gd_esquema.Maestra 
where MATERIAL_COD <> 'null'
group by MATERIAL_COD,MATERIAL_DESCRIPCION, MATERIAL_PRECIO
order by MATERIAL_DESCRIPCION


select TAREA_CODIGO, TAREA_DESCRIPCION, TAREA_FECHA_FIN, TAREA_FECHA_INICIO,TAREA_FECHA_INICIO_PLANIFICADO,TAREA_TIEMPO_ESTIMADO,TIPO_TAREA, count(material_cod)
from gd_esquema.Maestra where TAREA_DESCRIPCION <> 'null'
group by TAREA_CODIGO, TAREA_DESCRIPCION, TAREA_FECHA_FIN, TAREA_FECHA_INICIO,TAREA_FECHA_INICIO_PLANIFICADO,TAREA_TIEMPO_ESTIMADO,TIPO_TAREA
order by TAREA_CODIGO


